exports.seed = async function(knex) {
  await knex('users').del();
  await knex('candidates').del();
  await knex('interviews').del();
  await knex('documents').del();
  await knex('employees').del();

  const now = new Date();

  const userIds = await knex('users').insert([
    {
      email: 'admin@company.com',
      password_hash: '$2a$10$xVfYjKn0KkW0KkW0KkW0KO',
      role: 'admin',
      first_name: 'John',
      last_name: 'Admin',
      phone: '555-0100',
      is_active: true,
      created_at: now,
      updated_at: now,
    },
    {
      email: 'recruiter@company.com',
      password_hash: '$2a$10$xVfYjKn0KkW0KkW0KkW0KO',
      role: 'recruiter',
      first_name: 'Sarah',
      last_name: 'Recruiter',
      phone: '555-0101',
      is_active: true,
      created_at: now,
      updated_at: now,
    },
    {
      email: 'john.doe@email.com',
      password_hash: '$2a$10$xVfYjKn0KkW0KkW0KkW0KO',
      role: 'candidate',
      first_name: 'John',
      last_name: 'Doe',
      phone: '555-0102',
      is_active: true,
      created_at: now,
      updated_at: now,
    },
    {
      email: 'jane.smith@email.com',
      password_hash: '$2a$10$xVfYjKn0KkW0KkW0KkW0KO',
      role: 'candidate',
      first_name: 'Jane',
      last_name: 'Smith',
      phone: '555-0103',
      is_active: true,
      created_at: now,
      updated_at: now,
    },
    {
      email: 'mike.wilson@email.com',
      password_hash: '$2a$10$xVfYjKn0KkW0KkW0KkW0KO',
      role: 'candidate',
      first_name: 'Mike',
      last_name: 'Wilson',
      phone: '555-0104',
      is_active: true,
      created_at: now,
      updated_at: now,
    },
  ]).returning('id');

  const candidateIds = await knex('candidates').insert([
    {
      user_id: userIds[2].id,
      first_name: 'John',
      last_name: 'Doe',
      email: 'john.doe@email.com',
      phone: '555-0102',
      address: '123 Main St',
      city: 'New York',
      state: 'NY',
      zip_code: '10001',
      country: 'USA',
      date_of_birth: '1990-05-15',
      ssn_last_4: '1234',
      job_position: 'Electrician',
      status: 'interview',
      notes: 'Experienced electrician with 5+ years in commercial work',
      created_at: now,
      updated_at: now,
    },
    {
      user_id: userIds[3].id,
      first_name: 'Jane',
      last_name: 'Smith',
      email: 'jane.smith@email.com',
      phone: '555-0103',
      address: '456 Oak Ave',
      city: 'Los Angeles',
      state: 'CA',
      zip_code: '90001',
      country: 'USA',
      date_of_birth: '1985-08-22',
      ssn_last_4: '5678',
      job_position: 'Plumber',
      status: 'screening',
      notes: 'Licensed plumber looking for new opportunities',
      created_at: now,
      updated_at: now,
    },
    {
      user_id: userIds[4].id,
      first_name: 'Mike',
      last_name: 'Wilson',
      email: 'mike.wilson@email.com',
      phone: '555-0104',
      address: '789 Pine Rd',
      city: 'Chicago',
      state: 'IL',
      zip_code: '60601',
      country: 'USA',
      date_of_birth: '1988-03-10',
      ssn_last_4: '9012',
      job_position: 'Welder',
      status: 'hired',
      notes: 'Certified welder with AWS certification',
      created_at: now,
      updated_at: now,
    },
  ]).returning('id');

  await knex('interviews').insert([
    {
      candidate_id: candidateIds[0].id,
      interviewer_id: userIds[1].id,
      type: 'video',
      status: 'completed',
      scheduled_at: new Date('2024-01-15 10:00:00'),
      duration_minutes: 45,
      notes: 'Good communication skills, technical knowledge demonstrated',
      rating: 4,
      result: 'passed',
      created_at: now,
      updated_at: now,
    },
    {
      candidate_id: candidateIds[1].id,
      interviewer_id: userIds[1].id,
      type: 'phone',
      status: 'scheduled',
      scheduled_at: new Date('2024-02-01 14:00:00'),
      duration_minutes: 30,
      notes: 'Initial screening interview',
      created_at: now,
      updated_at: now,
    },
    {
      candidate_id: candidateIds[2].id,
      interviewer_id: userIds[1].id,
      type: 'in_person',
      status: 'completed',
      scheduled_at: new Date('2024-01-10 09:00:00'),
      duration_minutes: 60,
      notes: 'Excellent candidate, hired',
      rating: 5,
      result: 'passed',
      created_at: now,
      updated_at: now,
    },
  ]);

  await knex('documents').insert([
    {
      candidate_id: candidateIds[0].id,
      type: 'resume',
      file_name: 'john_doe_resume.pdf',
      file_path: '/uploads/candidates/1/resume.pdf',
      mime_type: 'application/pdf',
      file_size: 245000,
      status: 'approved',
      notes: 'Resume looks good',
      created_at: now,
      updated_at: now,
    },
    {
      candidate_id: candidateIds[0].id,
      type: 'id',
      file_name: 'john_doe_id.jpg',
      file_path: '/uploads/candidates/1/id.jpg',
      mime_type: 'image/jpeg',
      file_size: 120000,
      status: 'approved',
      created_at: now,
      updated_at: now,
    },
    {
      candidate_id: candidateIds[1].id,
      type: 'resume',
      file_name: 'jane_smith_resume.pdf',
      file_path: '/uploads/candidates/2/resume.pdf',
      mime_type: 'application/pdf',
      file_size: 198000,
      status: 'pending',
      created_at: now,
      updated_at: now,
    },
    {
      candidate_id: candidateIds[2].id,
      type: 'resume',
      file_name: 'mike_wilson_resume.pdf',
      file_path: '/uploads/candidates/3/resume.pdf',
      mime_type: 'application/pdf',
      file_size: 210000,
      status: 'approved',
      created_at: now,
      updated_at: now,
    },
    {
      candidate_id: candidateIds[2].id,
      type: 'contract',
      file_name: 'mike_wilson_contract.pdf',
      file_path: '/uploads/candidates/3/contract.pdf',
      mime_type: 'application/pdf',
      file_size: 156000,
      status: 'approved',
      notes: 'Signed contract on file',
      created_at: now,
      updated_at: now,
    },
  ]);

  await knex('employees').insert([
    {
      user_id: userIds[4].id,
      candidate_id: candidateIds[2].id,
      employee_id: 'EMP001',
      department: 'Manufacturing',
      position: 'Welder',
      hire_date: '2024-01-20',
      salary: 65000.00,
      employment_type: 'full_time',
      status: 'active',
      manager_name: 'Tom Manager',
      emergency_contact: 'Mary Wilson',
      emergency_phone: '555-0200',
      created_at: now,
      updated_at: now,
    },
  ]);
};
